CREATE TABLE IF NOT EXISTS USERS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CURRENT_INGREDIENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    count INT NOT NULL,
    user_id INT NOT NULL,
    CONSTRAINT ci_user FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS SAVED_INGREDIENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    order_value INT NOT NULL,
    user_id INT NOT NULL,
    CONSTRAINT si_user FOREIGN KEY (user_id) REFERENCES USERS(id)
);

INSERT INTO USERS (username, password) VALUES ('iendjei', '$2a$10$WT2PM4WDTB9XFPo.iyFbHeJ7dPbALpLttzqbfDukaPy9zV96huEbC');