CREATE TABLE IF NOT EXISTS CURRENT_INGREDIENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    count INT NOT NULL
);

CREATE TABLE IF NOT EXISTS SAVED_INGREDIENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    order_value INT NOT NULL
);